version: '3.7'

services:
  backend:
    build:
      context: ./api-backend
    ports:
      - "3000:3000"
    volumes:
      - ./api-backend:/api-backend
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: bicyle-shop

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:3000/api"
    depends_on:
      - backend

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bicycle-shop
    ports:
      - "3306:3306"
